# Generated by Django 4.0.3 on 2022-03-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
