# Generated by Django 4.0.3 on 2022-03-22 09:42

from django.db import migrations
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_customuser_address_remove_customuser_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+14150000000', max_length=128, region=None),
            preserve_default=False,
        ),
    ]
