# Generated by Django 4.0.3 on 2022-03-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profile_country_alter_profile_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='default.png', upload_to='profile/%Y/%m/%d'),
        ),
    ]
